---
name: Task - Build Rust

on:
  push:
  pull_request:

jobs:
  rust_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd rust

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: Build the project
        run: |
          cargo build --release