---
name: Task - Build Rust

on:
  push:
  pull_request:

jobs:
  rust_build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./rust
    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - working-directory: ${{ env.working-directory}}
        run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: Build the project
        working-directory: ${{ env.working-directory}}
        run: |
          cargo build --release